web/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Http;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$user = Http::withToken(session('jwt'))->get(env('API_ME'))->throw()->json();
	if(!array_key_exists('user', $user)){
    return view('welcome')->with(['user' => false]);
  }
  return view('welcome')->with(['user' => true]);
})->name('welcome');


Route::get('auth', 'AuthController@index')->name('auth');
Route::post('login', 'AuthController@login')->name('login');

Route::resource('user', 'UserController')->middleware(['auth','admin']);
Route::resource('client', 'ClientController')->middleware('auth');
Route::resource('contact', 'ContactController')->middleware('auth');
Route::resource('meeting', 'MeetingController')->middleware('auth');
Route::resource('support', 'SupportController')->middleware('auth');
Route::get('logout', 'AuthController@logout')->middleware('auth')->name('logout');
Route::get('home', 'HomeController@index')->middleware('auth')->name('home');
Route::post('report', 'ReportController@report')->middleware('auth')->name('report');

web/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel Web</title>

        <!-- Fonts -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">

        <!-- Styles -->
        <style>
            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }
            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }
            .center {
                margin: 0;
                position: absolute;
                top: 50%;
                left: 50%;
                -ms-transform: translate(-50%, -50%);
                transform: translate(-50%, -50%);
            }
        </style>
        @yield('style')

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/c179082552.js" crossorigin="anonymous"></script>
        @yield('script')

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ route('home') }}"><i class="fas fa-home"></i></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="modal" data-target="#reports_modal" href=""><i class="fas fa-clipboard-list"></i> Reports</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" data-toggle="dropdown">Options</a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('user.index') }}"><i class="fas fa-user"></i> User</a>
                            <a class="dropdown-item" href="{{ route('client.index') }}"><i class="fas fa-user-tie"></i> Client</a>
                            <a class="dropdown-item" href="{{ route('contact.index') }}"><i class="fas fa-address-book"></i> Contact</a>
                            <a class="dropdown-item" href="{{ route('support.index') }}"><i class="fas fa-ticket-alt"></i> Support Ticket</a>
                            <a class="dropdown-item" href="{{ route('meeting.index') }}"><i class="fas fa-handshake"></i> Meeting</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url('/logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container">
            @include('layouts.errors')

            @yield('content')

        </div>

        <!-- Modal -->
        @include('layouts.report_modal')

    </body>
</html>

web/resources/views/layouts/errors.blade.php
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif