web/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Http;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$user = Http::withToken(session('jwt'))->get(env('API_ME'))->throw()->json();
	if(!array_key_exists('user', $user)){
    return view('welcome')->with(['user' => false]);
  }
  return view('welcome')->with(['user' => true]);
})->name('welcome');


Route::get('auth', 'AuthController@index')->name('auth');
Route::post('login', 'AuthController@login')->name('login');

Route::resource('user', 'UserController')->middleware(['auth','admin']);
Route::resource('client', 'ClientController')->middleware('auth');
Route::resource('contact', 'ContactController')->middleware('auth');
Route::resource('meeting', 'MeetingController')->middleware('auth');
Route::resource('support', 'SupportController')->middleware('auth');
Route::get('logout', 'AuthController@logout')->middleware('auth')->name('logout');
Route::get('home', 'HomeController@index')->middleware('auth')->name('home');
Route::post('report', 'ReportController@report')->middleware('auth')->name('report');

web/app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

class ClientController extends Controller
{
    protected $sectors = [
        'educacion' => 'Educación',
        'industria' => 'Industria',
        'agricultura' => 'Agricultura',
        'manufactura' => 'Manufactura',
        'servicios' => 'Servicios',
        'otros' => 'Otros'
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = $this->get(env('API_CLIENT'));
        if(!array_key_exists('clients', $clients)){
          return view('client.index')->withErrors($clients['errors']);
        }
        if (empty($clients['clients'])) {
            return view('client.index')->with([
                'clients' => null, 
                'sectors' => $this->sectors
            ])->withErrors(['errors' => ['No clients in database']]);
        }
        return view('client.index')->with([
            'clients' => $clients['clients'], 
            'sectors' => $this->sectors
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.create')->with(['sectors' => $this->sectors]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'legal_certificate' => 'required|numeric|digits:10',
            'website' => 'required|max:255',
            'address' => 'required|max:255',
            'phone_number' => 'required|numeric|digits:8',
            'sector' => 'required|in:educacion,industria,agricultura,manufactura,servicios,otros'
        ]);
        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator->errors());
        }
        $client = $this->post(env('API_CLIENT'), $request->all());

        if(!array_key_exists('client', $client)){
          return Redirect::back()->withErrors($client['errors']);
        }
        return Redirect()->route('client.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = $this->get(env('API_CLIENT') . '/' . $id);
        if(!array_key_exists('client', $client)){
          return Redirect::back()->withErrors($client['errors']);
        }
        return view('client.delete')->with([
            'client' => $client['client'], 
            'sectors' => $this->sectors
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = $this->get(env('API_CLIENT') . '/' . $id);
        if(!array_key_exists('client', $client)){
          return Redirect::back()->withErrors($client['errors']);
        }
        return view('client.update')->with([
            'client' => $client['client'], 
            'sectors' => $this->sectors
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'legal_certificate' => 'required|digits:10',
            'website' => 'required|max:255',
            'address' => 'required|max:255',
            'phone_number' => 'required|digits:8',
            'sector' => 'required|in:educacion,industria,agricultura,manufactura,servicios,otros'
        ]);
        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator->errors());
        }
        $client = $this->put(env('API_CLIENT') . '/' . $id, $request->all());
        if(!array_key_exists('client', $client)){
          return Redirect::back()->withErrors($client['errors']);
        }
        return Redirect()->route('client.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = $this->delete(env('API_CLIENT') . '/' . $id);
        if(!array_key_exists('client', $client)){
          return Redirect::back()->withErrors($client['errors']);
        }
        return Redirect()->route('client.index');
    }
}

web/resources/views/client/create.blade.php
@extends('layouts.app')

@section('style')
  <style type="text/css">
    .card {
      width: 50%;
      left: 25%;
    }
  </style>
@endsection
    
@section('content')

  <div class="card">
    <div class="card-header">
      <h3>Create a new Client</h3>
    </div>
    <div class="card-body">
      {!! Form::open(['route' => 'client.store', 'method' => 'post']) !!}
        <div class="form-group">
          {!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
          {!! Form::text('name', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('legal_certificate', 'Legal Certificate:', ['class' => 'control-label']) !!}
          {!! Form::number('legal_certificate', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('website', 'Website:', ['class' => 'control-label']) !!}
          {!! Form::text('website', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('address', 'Address:', ['class' => 'control-label']) !!}
          {!! Form::text('address', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('phone_number', 'Phone Number:', ['class' => 'control-label']) !!}
          {!! Form::number('phone_number', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('sector', 'Sector:', ['class' => 'control-label']) !!}
          <select class="form-control" name="sector">
            @foreach(array_keys($sectors) as $sector_key)
              <option value='{{ $sector_key }}'>{{ $sectors[$sector_key] }}</option>
            @endforeach
            </select>
        </div>
    </div>
    <div class="card-footer">
      <div class="btn-group">
        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
        <a href="{{ route('client.index') }}" class="btn btn-secondary">Return</a>
      </div>
      {!! Form::close() !!}
    </div>
  </div>
    
@endsection

web/resources/views/client/delete.blade.php
@extends('layouts.app')

@section('style')
  <style type="text/css">
    .card {
      width: 50%;
      left: 25%;
    }
  </style>
@endsection
    
@section('content')

  <div class="card">
    <div class="card-header">
      <h3>Deleting Client: {{ $client['name'] }}</h3>
    </div>
    <div class="card-body">
      {!! Form::model($client, ['route' => ['client.destroy', $client['id']], 'method' => 'delete']) !!}
        <div class="form-group">
          {!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
          {!! Form::text('name', $client['name'], ['class' => 'form-control', 'disabled']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('legal_certificate', 'Legal Certificate:', ['class' => 'control-label']) !!}
          {!! Form::number('legal_certificate', $client['legal_certificate'], ['class' => 'form-control', 'disabled']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('website', 'Website:', ['class' => 'control-label']) !!}
          {!! Form::text('website', $client['website'], ['class' => 'form-control', 'disabled']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('address', 'Address:', ['class' => 'control-label']) !!}
          {!! Form::text('address', $client['address'], ['class' => 'form-control', 'disabled']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('phone_number', 'Phone Number:', ['class' => 'control-label']) !!}
          {!! Form::number('phone_number', $client['phone_number'], ['class' => 'form-control', 'disabled']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('sector', 'Sector:', ['class' => 'control-label', 'disabled']) !!}
          <select class="form-control" name="sector" disabled>
            @foreach(array_keys($sectors) as $sector_key)
              @if($sector_key == $client['sector'])
                <option value='{{ $sector_key }}' selected>{{ $sectors[$sector_key] }}</option>
              @else
                <option value='{{ $sector_key }}'>{{ $sectors[$sector_key] }}</option>
              @endif
            @endforeach
          </select>
        </div>
    </div>
    <div class="card-footer">
      <div class="btn-group">
        {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
        <a href="{{ route('client.index') }}" class="btn btn-secondary">Return</a>
      </div>
      {!! Form::close() !!}
    </div>
  </div>

@endsection

web/resources/views/client/index.blade.php
@extends('layouts.app')

@section('style')
    <style type="text/css">
        a .fas {
            color: black;
        }
        a .fas:hover {
            transform: scale(1.5);
        }
        .right {
            float: right;
        }
        .row {
            margin-bottom: 5px;
        }
    </style>
@endsection
    
@section('content')
    
    
    <div class="row">
        <div class="col-md-6">
            <h3>Clients</h3>
        </div>
        <div class="col-md-6">
            <a class="btn btn-primary right" href="{{ route('client.create') }}">New</a>
        </div>
    </div>

    @if($clients)
        <table class="table table-hover">
            <thead>
                <th>Name</th>
                <th>Legal Certificate</th>
                <th>Website</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Sector</th>
                <th>Options</th>
            </thead>
            <tbody>
                @foreach($clients as $client)
                    <tr>
                        <td>{{ $client['name'] }}</td>
                        <td>{{ $client['legal_certificate'] }}</td>
                        <td>{{ $client['website'] }}</td>
                        <td>{{ $client['address'] }}</td>
                        <td>{{ $client['phone_number'] }}</td>
                        <td>{{ $sectors[$client['sector']] }}</td>
                        <td>
                            <a href="{{ route('client.edit', [$client['id']]) }}" data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i></a>
                             - 
                            <a href="{{ route('client.show', [$client['id']]) }}" data-toggle="tooltip" title="Delete"><i class="fas fa-eraser"></i></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

@endsection

web/resources/views/client/update.blade.php
@extends('layouts.app')

@section('style')
  <style type="text/css">
    .card {
      width: 50%;
      left: 25%;
    }
  </style>
@endsection
    
@section('content')
    
  <div class="card">
    <div class="card-header">
      <h3>Updating Client: {{ $client['name'] }}</h3>
    </div>
    <div class="card-body">
      {!! Form::model($client, ['route' => ['client.update', $client['id']], 'method' => 'put']) !!}
        <div class="form-group">
          {!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
          {!! Form::text('name', $client['name'], ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('legal_certificate', 'Legal Certificate:', ['class' => 'control-label']) !!}
          {!! Form::number('legal_certificate', $client['legal_certificate'], ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('website', 'Website:', ['class' => 'control-label']) !!}
          {!! Form::text('website', $client['website'], ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('address', 'Address:', ['class' => 'control-label']) !!}
          {!! Form::text('address', $client['address'], ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('phone_number', 'Phone Number:', ['class' => 'control-label']) !!}
          {!! Form::number('phone_number', $client['phone_number'], ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('sector', 'Sector:', ['class' => 'control-label']) !!}
          <select class="form-control" name="sector">
            @foreach(array_keys($sectors) as $sector_key)
              @if($sector_key == $client['sector'])
                <option value='{{ $sector_key }}' selected>{{ $sectors[$sector_key] }}</option>
              @else
                <option value='{{ $sector_key }}'>{{ $sectors[$sector_key] }}</option>
              @endif
            @endforeach
          </select>
        </div>
    </div>
    <div class="card-footer">
      <div class="btn-group">
        {!! Form::submit('Update', ['class' => 'btn btn-success']) !!}
        <a href="{{ route('client.index') }}" class="btn btn-secondary">Return</a>
      </div>
      {!! Form::close() !!}
    </div>
  </div>

@endsection