web/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Http;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$user = Http::withToken(session('jwt'))->get(env('API_ME'))->throw()->json();
	if(!array_key_exists('user', $user)){
    return view('welcome')->with(['user' => false]);
  }
  return view('welcome')->with(['user' => true]);
})->name('welcome');


Route::get('auth', 'AuthController@index')->name('auth');
Route::post('login', 'AuthController@login')->name('login');

Route::resource('user', 'UserController')->middleware(['auth','admin']);
Route::resource('client', 'ClientController')->middleware('auth');
Route::resource('contact', 'ContactController')->middleware('auth');
Route::resource('meeting', 'MeetingController')->middleware('auth');
Route::resource('support', 'SupportController')->middleware('auth');
Route::get('logout', 'AuthController@logout')->middleware('auth')->name('logout');
Route::get('home', 'HomeController@index')->middleware('auth')->name('home');
Route::post('report', 'ReportController@report')->middleware('auth')->name('report');

web/app/Http/Controllers/MeetingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

class MeetingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $meetings = $this->get(env('API_MEETING'));
        if(!array_key_exists('meetings', $meetings)){
          return view('meeting.index')->withErrors($meetings['errors']);
        }
        if (empty($meetings['meetings'])) {
            return view('meeting.index')->with(['meetings' => null])->withErrors(['errors' => ['No meetings in database']]);
        }
        return view('meeting.index')->with([
            'meetings' => $meetings['meetings'],
            'meetings_users' => $meetings['meetings_users'],
            'clients' => $meetings['clients']
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = $this->get(env('API_CLIENT'));
        if(!array_key_exists('clients', $clients)){
            return view('meeting.create')->withErrors($clients['errors']);
        }
        if (empty($clients['clients'])) {
            return view('meeting.create')->withErrors(['No clients in database']);
        }
        $users = $this->get(env('API_USER'));
        if(!array_key_exists('users', $users)){
            return view('meeting.create')->withErrors($users['errors']);
        }
        if (empty($users['users'])) {
            return view('meeting.create')->withErrors(['No users in database']);
        }
        return view('meeting.create')->with([
            'clients' => $clients['clients'],
            'users' => $users['users']
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|max:255',
            'date' => 'required|date|after:today',
            'time' => 'required|date_format:H:i',
            'virtual' => 'in:on,null',
            'user_ids' => 'required|array'
        ]);
        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator->errors());
        }
        $meeting = $this->post(env('API_MEETING'), $request->all());
        if(!array_key_exists('meeting', $meeting)){
            return Redirect::back()->withErrors($meeting['errors']);
        }
        return Redirect()->route('meeting.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $meeting = $this->get(env('API_MEETING') . '/' . $id);
      if(!array_key_exists('meeting', $meeting)){
        return Redirect::back()->withErrors($meeting['errors']);
      }
      $clients = $this->get(env('API_CLIENT'));
      if(!array_key_exists('clients', $clients)){
          return view('meeting.update')->withErrors($clients['errors']);
      }
      if (empty($clients['clients'])) {
          return view('meeting.update')->withErrors(['errors' => ['No clients in database']]);
      }
      $users = $this->get(env('API_USER'));
      if(!array_key_exists('users', $users)){
          return view('meeting.update')->withErrors($users['errors']);
      }
      if (empty($users['users'])) {
          return view('meeting.update')->withErrors(['No users in database']);
      }
      return view('meeting.delete')->with([
          'meeting' => $meeting['meeting'],
          'meeting_users' => $meeting['meeting_users'],
          'clients' => $clients['clients'],
          'users' => $users['users']
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $meeting = $this->get(env('API_MEETING') . '/' . $id);
      if(!array_key_exists('meeting', $meeting)){
        return Redirect::back()->withErrors($meeting['errors']);
      }
      $clients = $this->get(env('API_CLIENT'));
      if(!array_key_exists('clients', $clients)){
          return view('meeting.update')->withErrors($clients['errors']);
      }
      if (empty($clients['clients'])) {
          return view('meeting.update')->withErrors(['errors' => ['No clients in database']]);
      }
      $users = $this->get(env('API_USER'));
      if(!array_key_exists('users', $users)){
          return view('meeting.update')->withErrors($users['errors']);
      }
      if (empty($users['users'])) {
          return view('meeting.update')->withErrors(['No users in database']);
      }
      return view('meeting.update')->with([
          'meeting' => $meeting['meeting'],
          'meeting_users' => $meeting['meeting_users'],
          'clients' => $clients['clients'],
          'users' => $users['users']
      ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|max:255',
            'date' => 'required|date',
            'time' => 'required|date_format:H:i',
            'virtual' => 'in:on,null',
            'user_ids' => 'required|array'
        ]);
        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator->errors());
        }
        $meeting = $this->put(env('API_MEETING') . '/' . $id, $request->all());
        if(!array_key_exists('meeting', $meeting)){
            $clients = $this->get(env('API_CLIENT'));
            if(!array_key_exists('clients', $clients)){
                return Redirect::back()->withErrors($meeting['errors'].push($clients['errors']));
            }
            if (empty($clients['clients'])) {
                return Redirect::back()->withErrors($meeting['errors'].push('No clients in database'));
            }
            return Redirect::back()->withErrors($meeting['errors']);
        }
        return Redirect()->route('meeting.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $meeting = $this->delete(env('API_MEETING') . '/' . $id);
        if(!array_key_exists('meeting', $meeting)){
          return Redirect::back()->withErrors($meeting['errors']);
        }
        return Redirect()->route('meeting.index');
    }
}

web/resources/views/meeting/create.blade.php
@extends('layouts.app')

@section('style')
  <style type="text/css">
    .card {
      width: 50%;
      left: 25%;
    }
  </style>
@endsection
    
@section('content')

  <div class="card">
    <div class="card-header">
      <h3>Create a new Meeting</h3>
    </div>
    <div class="card-body">
      {!! Form::open(['route' => 'meeting.store', 'method' => 'post']) !!}
        <div class="form-group">
          {!! Form::label('client_id', 'Client:', ['class' => 'control-label']) !!}
          <select class="form-control" name="client_id">
            @if($clients)
              <option value='null'>-- Click to select a client --</option>
              @foreach($clients as $client)
                <option value="{{ $client['id'] }}">{{ $client['name'] }}</option>
              @endforeach
            @else
              <option value='null'>-- No Clients Available --</option>
            @endif            
          </select>
        </div>
        <div class="form-group">
          {!! Form::label('title', 'Title:', ['class' => 'control-label']) !!}
          {!! Form::text('title', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('date', 'Date:', ['class' => 'control-label']) !!}
          {!! Form::date('date', \Carbon\Carbon::now()->format('Y-m-d'), ['class' => 'form-control', 'required' => 'true', 'min' => \Carbon\Carbon::now()->format('Y-m-d')]) !!}
        </div>
        <div class="form-group">
          {!! Form::label('time', 'Time:', ['class' => 'control-label']) !!}
          {!! Form::time('time', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          <div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="virtual" name="virtual">
            {!! Form::label('virtual', 'Virtual', ['class' => 'custom-control-label']) !!}
          </div>
        </div>
        <div class="form-group">
          {!! Form::label('user_ids', 'Users:', ['class' => 'control-label']) !!}
          <select class="custom-select" name="user_ids[]" size="4" multiple>
            @if($users)
              @foreach($users as $user)
                <option value="{{ $user['id'] }}">{{ $user['username'] }}</option>
              @endforeach
            @else
              <option value='0'>-- No Users Available --</option>
            @endif            
          </select>
        </div>
    </div>
    <div class="card-footer">
      <div class="btn-group">
        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
        <a href="{{ route('meeting.index') }}" class="btn btn-secondary">Return</a>
      </div>
      {!! Form::close() !!}
    </div>
  </div>
    
@endsection

web/resources/views/meeting/delete.blade.php
@extends('layouts.app')

@section('style')
  <style type="text/css">
    .card {
      width: 50%;
      left: 25%;
    }
  </style>
@endsection
    
@section('content')

  <div class="card">
    <div class="card-header">
      <h3>Deleting Meeting: #{{ $meeting['id'] }}</h3>
    </div>
    <div class="card-body">
      {!! Form::model($meeting, ['route' => ['meeting.destroy', $meeting['id']], 'method' => 'delete']) !!}
        <div class="form-group">
          {!! Form::label('client_id', 'Client:', ['class' => 'control-label']) !!}
          <select class="form-control" name="client_id" disabled>
            @if($clients)
              <option value='null'>-- Not Selected --</option>
              @foreach($clients as $client)
                @if($client['id'] == $meeting['client_id'])
                  <option value="{{ $client['id'] }}" selected>{{ $client['name'] }}</option>
                @else
                  <option value="{{ $client['id'] }}">{{ $client['name'] }}</option>
                @endif
              @endforeach
            @else
              <option value='null'>-- No Clients Available --</option>
            @endif            
          </select>
        </div>
        <div class="form-group">
          {!! Form::label('title', 'Title:', ['class' => 'control-label']) !!}
          {!! Form::text('title', $meeting['title'] , ['class' => 'form-control', 'disabled']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('date', 'Date:', ['class' => 'control-label']) !!}
          {!! Form::date('date', date('Y-m-d', strtotime($meeting['date_time'])), ['class' => 'form-control', 'disabled', 'min' => \Carbon\Carbon::now()->format('Y-m-d')]) !!}
        </div>
        <div class="form-group">
          {!! Form::label('time', 'Time:', ['class' => 'control-label']) !!}
          {!! Form::time('time', date('H:i', strtotime($meeting['date_time'])), ['class' => 'form-control', 'disabled']) !!}
        </div>
        <div class="form-group">
          <div class="custom-control custom-switch">
            @if($meeting['virtual'])
              <input type="checkbox" class="custom-control-input" id="virtual" name="virtual" checked disabled>
            @else
              <input type="checkbox" class="custom-control-input" id="virtual" name="virtual" disabled>
            @endif
            {!! Form::label('virtual', 'Virtual', ['class' => 'custom-control-label']) !!}
          </div>
        </div>
        <div class="form-group">
          {!! Form::label('user_ids', 'Users:', ['class' => 'control-label']) !!}
          <select class="custom-select" name="user_ids[]" size="4" disabled>
            @if($users)
              @if($meeting_users)
                @foreach($users as $user)
                  @if(in_array($user['username'], explode(' - ', $meeting_users)))
                    <option value="{{ $user['id'] }}" selected>{{ $user['username'] }}</option>
                  @else
                    <option value="{{ $user['id'] }}">{{ $user['username'] }}</option>
                  @endif
                @endforeach
              @else
                @foreach($users as $user)
                  <option value="{{ $user['id'] }}">{{ $user['username'] }}</option>
                @endforeach
              @endif
            @else
              <option value='0'>-- No Users Available --</option>
            @endif            
          </select>
        </div>
    </div>
    <div class="card-footer">
      <div class="btn-group">
        {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
        <a href="{{ route('meeting.index') }}" class="btn btn-secondary">Return</a>
      </div>
      {!! Form::close() !!}
    </div>
  </div>

@endsection

web/resources/views/meeting/index.blade.php
@extends('layouts.app')

@section('style')
    <style type="text/css">
        a .fas {
            color: black;
        }
        a .fas:hover {
            transform: scale(1.5);
        }
        .right {
            float: right;
        }
        .row {
            margin-bottom: 5px;
        }
    </style>
@endsection
    
@section('content')
    
    
    <div class="row">
        <div class="col-md-6">
            <h3>Meetings</h3>
        </div>
        <div class="col-md-6">
            <a class="btn btn-primary right" href="{{ route('meeting.create') }}">New</a>
        </div>
    </div>

    @if($meetings)
        <table class="table table-hover">
            <thead>
                <th>Client</th>
                <th>Title</th>
                <th>DateTime</th>
                <th>Virtual</th>
                <th>Users</th>
                <th>Options</th>
            </thead>
            <tbody>
                @foreach($meetings as $meeting)
                    <tr>
                        @if($meeting['client_id'])
                            <td>{{ $clients[$meeting['client_id'] . ' '] }}</td>
                        @else
                            <td>Not Available</td>
                        @endif
                        <td>{{ $meeting['title'] }}</td>
                        <td>{{ $meeting['date_time'] }}</td>
                        @if($meeting['virtual'] == 1)
                            <td>Yes</td>
                        @else
                            <td>No</td>
                        @endif
                        @if(in_array($meeting['id'], array_keys($meetings_users)))
                            <td>{{ $meetings_users[$meeting['id'] . ' '] }}</td>
                        @else
                            <td>Miising Users</td>
                        @endif
                        <td>
                            <a href="{{ route('meeting.edit', [$meeting['id']]) }}" data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i></a>
                             - 
                            <a href="{{ route('meeting.show', [$meeting['id']]) }}" data-toggle="tooltip" title="Delete"><i class="fas fa-eraser"></i></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

@endsection

web/resources/views/meeting/update.blade.php
@extends('layouts.app')

@section('style')
  <style type="text/css">
    .card {
      width: 50%;
      left: 25%;
    }
  </style>
@endsection
    
@section('content')
    
  <div class="card">
    <div class="card-header">
      <h3>Updating Meeting: #{{ $meeting['id'] }}</h3>
    </div>
    <div class="card-body">
      {!! Form::model($meeting, ['route' => ['meeting.update', $meeting['id']], 'method' => 'put']) !!}
        <div class="form-group">
          {!! Form::label('client_id', 'Client:', ['class' => 'control-label']) !!}
          <select class="form-control" name="client_id">
            @if($clients)
              <option value='null'>-- Click to select a client --</option>
              @foreach($clients as $client)
                @if($client['id'] == $meeting['client_id'])
                  <option value="{{ $client['id'] }}" selected>{{ $client['name'] }}</option>
                @else
                  <option value="{{ $client['id'] }}">{{ $client['name'] }}</option>
                @endif
              @endforeach
            @else
              <option value='null'>-- No Clients Available --</option>
            @endif            
          </select>
        </div>
        <div class="form-group">
          {!! Form::label('title', 'Title:', ['class' => 'control-label']) !!}
          {!! Form::text('title', $meeting['title'] , ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('date', 'Date:', ['class' => 'control-label']) !!}
          {!! Form::date('date', date('Y-m-d', strtotime($meeting['date_time'])), ['class' => 'form-control', 'required' => 'true', 'min' => \Carbon\Carbon::now()->format('Y-m-d')]) !!}
        </div>
        <div class="form-group">
          {!! Form::label('time', 'Time:', ['class' => 'control-label']) !!}
          {!! Form::time('time', date('H:i', strtotime($meeting['date_time'])), ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          <div class="custom-control custom-switch">
            @if($meeting['virtual'])
              <input type="checkbox" class="custom-control-input" id="virtual" name="virtual" checked>
            @else
              <input type="checkbox" class="custom-control-input" id="virtual" name="virtual">
            @endif
            {!! Form::label('virtual', 'Virtual', ['class' => 'custom-control-label']) !!}
          </div>
        </div>
        <div class="form-group">
          {!! Form::label('user_ids', 'Users:', ['class' => 'control-label']) !!}
          <select class="custom-select" name="user_ids[]" size="4" multiple>
            @if($users)
              @if($meeting_users)
                @foreach($users as $user)
                  @if(in_array($user['username'], explode(' - ', $meeting_users)))
                    <option value="{{ $user['id'] }}" selected>{{ $user['username'] }}</option>
                  @else
                    <option value="{{ $user['id'] }}">{{ $user['username'] }}</option>
                  @endif
                @endforeach
              @else
                @foreach($users as $user)
                  <option value="{{ $user['id'] }}">{{ $user['username'] }}</option>
                @endforeach
              @endif
            @else
              <option value='0'>-- No Users Available --</option>
            @endif            
          </select>
        </div>
    </div>
    <div class="card-footer">
      <div class="btn-group">
        {!! Form::submit('Update', ['class' => 'btn btn-success']) !!}
        <a href="{{ route('meeting.index') }}" class="btn btn-secondary">Return</a>
      </div>
      {!! Form::close() !!}
    </div>
  </div>

@endsection