web/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Http;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$user = Http::withToken(session('jwt'))->get(env('API_ME'))->throw()->json();
	if(!array_key_exists('user', $user)){
    return view('welcome')->with(['user' => false]);
  }
  return view('welcome')->with(['user' => true]);
})->name('welcome');


Route::get('auth', 'AuthController@index')->name('auth');
Route::post('login', 'AuthController@login')->name('login');

Route::resource('user', 'UserController')->middleware(['auth','admin']);
Route::resource('client', 'ClientController')->middleware('auth');
Route::resource('contact', 'ContactController')->middleware('auth');
Route::resource('meeting', 'MeetingController')->middleware('auth');
Route::resource('support', 'SupportController')->middleware('auth');
Route::get('logout', 'AuthController@logout')->middleware('auth')->name('logout');
Route::get('home', 'HomeController@index')->middleware('auth')->name('home');
Route::post('report', 'ReportController@report')->middleware('auth')->name('report');

web/app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = $this->get(env('API_CONTACT'));
        if(!array_key_exists('contacts', $contacts)){
          return view('contact.index')->withErrors($contacts['errors']);
        }
        if (empty($contacts['contacts'])) {
            return view('contact.index')->with(['contacts' => null])->withErrors(['errors' => ['No contacts in database']]);
        }
        return view('contact.index')->with([
            'contacts' => $contacts['contacts'],
            'clients' => $contacts['clients']
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = $this->get(env('API_CLIENT'));
        if(!array_key_exists('clients', $clients)){
            return view('contact.create')->withErrors($clients['errors']);
        }
        if (empty($clients['clients'])) {
            return view('contact.create')->withErrors(['No clients in database']);
        }
        return view('contact.create')->with(['clients' => $clients['clients']]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'client_id' => 'required',
            'name' => 'required|max:255',
            'lastnames' => 'required|max:255',
            'email' => 'required|max:255|email',
            'phone_number' => 'required|numeric|digits:8',
            'job' => 'required|max:255'
        ]);
        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator->errors());
        }
        $contact = $this->post(env('API_CONTACT'), $request->all());
        if(!array_key_exists('contact', $contact)){
            $clients = $this->get(env('API_CLIENT'));
            if(!array_key_exists('clients', $clients)){
                return Redirect::back()->withErrors($contact['errors'].push($clients['errors']));
            }
            if (empty($clients['clients'])) {
                return Redirect::back()->withErrors($contact['errors'].push('No clients in database'));
            }
            return Redirect::back()->withErrors($contact['errors']);
        }
        return Redirect()->route('contact.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contact = $this->get(env('API_CONTACT') . '/' . $id);
        if(!array_key_exists('contact', $contact)){
          return Redirect::back()->withErrors($contact['errors']);
        }
        $clients = $this->get(env('API_CLIENT'));
        if(!array_key_exists('clients', $clients)){
            return view('contact.delete')->withErrors($clients['errors']);
        }
        if (empty($clients['clients'])) {
            return view('contact.delete')->withErrors(['errors' => ['No clients in database']]);
        }
        return view('contact.delete')->with([
            'contact' => $contact['contact'], 
            'clients' => $clients['clients']
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact = $this->get(env('API_CONTACT') . '/' . $id);
        if(!array_key_exists('contact', $contact)){
          return Redirect::back()->withErrors($contact['errors']);
        }
        $clients = $this->get(env('API_CLIENT'));
        if(!array_key_exists('clients', $clients)){
            return view('contact.update')->withErrors($clients['errors']);
        }
        if (empty($clients['clients'])) {
            return view('contact.update')->withErrors(['errors' => ['No clients in database']]);
        }
        return view('contact.update')->with([
            'contact' => $contact['contact'], 
            'clients' => $clients['clients']
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'client_id' => 'required',
            'name' => 'required|max:255',
            'lastnames' => 'required|max:255',
            'email' => 'required|max:255|email',
            'phone_number' => 'required|numeric|digits:8',
            'job' => 'required|max:255'
        ]);
        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator->errors());
        }
        $contact = $this->put(env('API_CONTACT') . '/' . $id, $request->all());
        if(!array_key_exists('contact', $contact)){
            $clients = $this->get(env('API_CLIENT'));
            if(!array_key_exists('clients', $clients)){
                return Redirect::back()->withErrors($contact['errors'].push($clients['errors']));
            }
            if (empty($clients['clients'])) {
                return Redirect::back()->withErrors($contact['errors'].push('No clients in database'));
            }
            return Redirect::back()->withErrors($contact['errors']);
        }
        return Redirect()->route('contact.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = $this->delete(env('API_CONTACT') . '/' . $id);
        if(!array_key_exists('contact', $contact)){
          return Redirect::back()->withErrors($contact['errors']);
        }
        return Redirect()->route('contact.index');
    }
}

web/resources/views/contact/create.blade.php
@extends('layouts.app')

@section('style')
  <style type="text/css">
    .card {
      width: 50%;
      left: 25%;
    }
  </style>
@endsection
    
@section('content')

  <div class="card">
    <div class="card-header">
      <h3>Create a new Contact</h3>
    </div>
    <div class="card-body">
      {!! Form::open(['route' => 'contact.store', 'method' => 'post']) !!}
        <div class="form-group">
          {!! Form::label('client_id', 'Contact:', ['class' => 'control-label']) !!}
          <select class="form-control" name="client_id">
            @if($clients)
              @foreach($clients as $client)
                <option value="{{ $client['id'] }}">{{ $client['name'] }}</option>
              @endforeach
            @else
              <option value='0'>-- No Clients Available --</option>
            @endif            
          </select>
        </div>
        <div class="form-group">
          {!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
          {!! Form::text('name', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('lastnames', 'Surnames:', ['class' => 'control-label']) !!}
          {!! Form::text('lastnames', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('email', 'Email:', ['class' => 'control-label']) !!}
          {!! Form::email('email', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('phone_number', 'Phone Number:', ['class' => 'control-label']) !!}
          {!! Form::number('phone_number', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('job', 'Job:', ['class' => 'control-label']) !!}
          {!! Form::text('job', '', ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
    </div>
    <div class="card-footer">
      <div class="btn-group">
        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
        <a href="{{ route('contact.index') }}" class="btn btn-secondary">Return</a>
      </div>
      {!! Form::close() !!}
    </div>
  </div>
    
@endsection

web/resources/views/contact/delete.blade.php
@extends('layouts.app')

@section('style')
  <style type="text/css">
    .card {
      width: 50%;
      left: 25%;
    }
  </style>
@endsection
    
@section('content')

  <div class="card">
    <div class="card-header">
      <h3>Deleting contact: {{ $contact['name'] }}</h3>
    </div>
    <div class="card-body">
      {!! Form::model($contact, ['route' => ['contact.destroy', $contact['id']], 'method' => 'delete']) !!}
        <div class="form-group">
          {!! Form::label('client_id', 'Client:', ['class' => 'control-label']) !!}
          <select class="form-control" name="client_id" disabled>
            @if($clients)
              @foreach($clients as $client)
                @if($client['id'] == $contact['client_id'])
                  <option value="{{ $client['id'] }}" selected>{{ $client['name'] }}</option>
                @else
                  <option value="{{ $client['id'] }}">{{ $client['name'] }}</option>
                @endif
              @endforeach
            @else
              <option value='0'>-- No Clients Available --</option>
            @endif            
          </select>
        </div>
        <div class="form-group">
          {!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
          {!! Form::text('name', $contact['name'], ['class' => 'form-control', ' disabled']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('lastnames', 'Surnames:', ['class' => 'control-label']) !!}
          {!! Form::text('lastnames', $contact['lastnames'], ['class' => 'form-control', ' disabled']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('email', 'Email:', ['class' => 'control-label']) !!}
          {!! Form::email('email', $contact['email'], ['class' => 'form-control', ' disabled']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('phone_number', 'Phone Number:', ['class' => 'control-label']) !!}
          {!! Form::number('phone_number', $contact['phone_number'], ['class' => 'form-control', ' disabled']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('job', 'Job:', ['class' => 'control-label']) !!}
          {!! Form::text('job', $contact['job'], ['class' => 'form-control', ' disabled']) !!}
        </div>
    </div>
    <div class="card-footer">
      <div class="btn-group">
        {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
        <a href="{{ route('contact.index') }}" class="btn btn-secondary">Return</a>
      </div>
      {!! Form::close() !!}
    </div>
  </div>

@endsection

web/resources/views/contact/index.blade.php
@extends('layouts.app')

@section('style')
    <style type="text/css">
        a .fas {
            color: black;
        }
        a .fas:hover {
            transform: scale(1.5);
        }
        .right {
            float: right;
        }
        .row {
            margin-bottom: 5px;
        }
    </style>
@endsection
    
@section('content')
    
    
    <div class="row">
        <div class="col-md-6">
            <h3>Contacts</h3>
        </div>
        <div class="col-md-6">
            <a class="btn btn-primary right" href="{{ route('contact.create') }}">New</a>
        </div>
    </div>

    @if($contacts)
        <table class="table table-hover">
            <thead>
                <th>Client</th>
                <th>Name</th>
                <th>Surnames</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Job</th>
                <th>Options</th>
            </thead>
            <tbody>
                @foreach($contacts as $contact)
                    <tr>
                        <td>{{ $clients[$contact['client_id'] . ' '] }}</td>
                        <td>{{ $contact['name'] }}</td>
                        <td>{{ $contact['lastnames'] }}</td>
                        <td>{{ $contact['email'] }}</td>
                        <td>{{ $contact['phone_number'] }}</td>
                        <td>{{ $contact['job'] }}</td>
                        <td>
                            <a href="{{ route('contact.edit', [$contact['id']]) }}" data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i></a>
                             - 
                            <a href="{{ route('contact.show', [$contact['id']]) }}" data-toggle="tooltip" title="Delete"><i class="fas fa-eraser"></i></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

@endsection

web/resources/views/contact/update.blade.php
@extends('layouts.app')

@section('style')
  <style type="text/css">
    .card {
      width: 50%;
      left: 25%;
    }
  </style>
@endsection
    
@section('content')
    
  <div class="card">
    <div class="card-header">
      <h3>Updating Contact: {{ $contact['name'] }}</h3>
    </div>
    <div class="card-body">
      {!! Form::model($contact, ['route' => ['contact.update', $contact['id']], 'method' => 'put']) !!}
        <div class="form-group">
          {!! Form::label('client_id', 'Client:', ['class' => 'control-label']) !!}
          <select class="form-control" name="client_id">
            @if($clients)
              @foreach($clients as $client)
                @if($client['id'] == $contact['client_id'])
                  <option value="{{ $client['id'] }}" selected>{{ $client['name'] }}</option>
                @else
                  <option value="{{ $client['id'] }}">{{ $client['name'] }}</option>
                @endif
              @endforeach
            @else
              <option value='0'>-- No Clients Available --</option>
            @endif            
          </select>
        </div>
        <div class="form-group">
          {!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
          {!! Form::text('name', $contact['name'], ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('lastnames', 'Surnames:', ['class' => 'control-label']) !!}
          {!! Form::text('lastnames', $contact['lastnames'], ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('email', 'Email:', ['class' => 'control-label']) !!}
          {!! Form::email('email', $contact['email'], ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('phone_number', 'Phone Number:', ['class' => 'control-label']) !!}
          {!! Form::number('phone_number', $contact['phone_number'], ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
        <div class="form-group">
          {!! Form::label('job', 'Job:', ['class' => 'control-label']) !!}
          {!! Form::text('job', $contact['job'], ['class' => 'form-control', 'required' => 'true']) !!}
        </div>
    </div>
    <div class="card-footer">
      <div class="btn-group">
        {!! Form::submit('Update', ['class' => 'btn btn-success']) !!}
        <a href="{{ route('contact.index') }}" class="btn btn-secondary">Return</a>
      </div>
      {!! Form::close() !!}
    </div>
  </div>

@endsection